#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Empowered.Dataverse.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class ServiceContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public ServiceContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Empowered.Dataverse.Model.Organization"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Empowered.Dataverse.Model.Organization> OrganizationSet
		{
			get
			{
				return this.CreateQuery<Empowered.Dataverse.Model.Organization>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Empowered.Dataverse.Model.Solution"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Empowered.Dataverse.Model.Solution> SolutionSet
		{
			get
			{
				return this.CreateQuery<Empowered.Dataverse.Model.Solution>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Empowered.Dataverse.Model.SolutionComponent"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Empowered.Dataverse.Model.SolutionComponent> SolutionComponentSet
		{
			get
			{
				return this.CreateQuery<Empowered.Dataverse.Model.SolutionComponent>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Empowered.Dataverse.Model.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Empowered.Dataverse.Model.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<Empowered.Dataverse.Model.SystemUser>();
			}
		}
	}
}
#pragma warning restore CS1591
